project_id = "polzdhlstwdvzmyxflrk"

[functions.send-lead-webhook]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.extract-metrics-from-image]
verify_jwt = true

[functions.generate-property-description]
verify_jwt = true

[functions.sync-arbo-imoveis]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false
